name: Release build

on:
  push:
    branches:
      - fork
      - main
      - release-pipeline

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        include:
          - os: macos-latest
            name: mac
            files_to_upload: |
              arm64_mac.dmg
              x64_mac.dmg
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm install

    - name: Build the Electron app
      run: npm run build:electron:${{ matrix.name }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bruno_1.27.0-${{ matrix.name }}
        path: packages/bruno-electron/out/bruno_(.*)dmg

        