name: Release

on:
  push:
    tags:
      - '*'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get the version
        id: tag
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        run: echo $VERSION
        env:
          VERSION: ${{ steps.tag.outputs.tag }}

  build:
    runs-on: ${{ matrix.os }}
    needs: version
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        include:
          - os: macos-latest
            name: mac
          - os: ubuntu-latest
            name: linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Build the Electron app
      run: npm run build:electron:${{ matrix.name }}

    - uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.name }}
        path: |
          ./packages/bruno-electron/out/*.dmg
          ./packages/bruno-electron/out/*.AppImage

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Retrieve saved linux artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-linux
        path: ./packages/bruno-electron/out/*
    - name: Retrieve saved mac artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-mac
        path: ./packages/bruno-electron/out/*
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./packages/bruno-electron/out/*.dmg
          ./packages/bruno-electron/out/*.AppImage
        draft: true


